name = "htmx_tailwind_gleam_app"
version = "0.0.0"
description = "A simple project using htmx, Tailwind CSS, and Gleam."

[dependencies]
gleam_stdlib = ">= 0.34.0"
gleam_http = ">= 3.0.0"
gleam_httpc = ">= 1.0.0"
gleam_json = ">= 1.0.0"
mist = ">= 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
